title: Katie DeGroot
description: The work of artist Katie DeGroot
url: //katiedegroot.com
baseurl: ""

port: 4000
host: 127.0.0.1
sass:
  sass_dir: _scss
  style: :compressed
lsi: false
markdown: kramdown
source: .
destination: _site
permalink: /:categories/:year/:title/
timezone: America/New_York

exclude: [node_modules, '.sass-cache', Gemfile, Gemfile.lock, README.md, package.json, Gruntfile.js, .scss-lint.yml]

collections:
  content:
    output: true
  prints:
    output: true
